name: Java CI

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Test with Maven
      run: mvn test

    - name: Notify on Success
      if: success()
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{"chat_id": "1098482972", "text": "Все тесты прошли успешно."}' https://api.telegram.org/bot6843364517:AAG19zIZfByrqsMfsbHaaFtPAlnhdLUYC-Q/sendMessage


    - name: Notify on Failure
      if: failure()
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{"chat_id": "1098482972", "text": "Ошибка в тестах, проверьте результаты."}' https://api.telegram.org/bot6843364517:AAG19zIZfByrqsMfsbHaaFtPAlnhdLUYC-Q/sendMessage
